<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<title>Search the collections</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="author" content="Tibus - [ ebusiness | interactive | networks ]" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<link rel="StyleSheet" href="/css/layout.css" type="text/css" />
<link rel="StyleSheet" href="/css/text.css" type="text/css" />
<!--[if IE 5]>
<style type="text/css">
td {
   font-size: 70%;
}
</style>
<![endif]-->
<style type="text/css">
<!--
.style2 {font-size: 9px}
.style10 {font-size: small}
.style6 {color: #000000}
.style7 {	font-size: small;
	color: #000000;
	font-weight: bold;
}
-->
</style>
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->

</script>
</head>
<body>

<!-- Start TOP BOX -->
<div id="topboxoutter">
  <div id="topbox">
    <div><img src="/images/arts_council_logo.gif" width="150" height="99" alt="arts council of Northern Ireland Logo" border="0" /></div>
    <div id="sitesearchbox">
    <form method="get" action="http://search2.nics.gov.uk/kbroker/artscouncil/search.sim">
	<table class="searchform" border="0">
    	<tr>

			<td nowrap>
	        <input type="text" name="qt" size="10" maxlength="1000" value="" />&nbsp;<input id="submit" type="submit" value="Search" />
        	<input type="hidden" name="sr" value="0" />
	        <input type="hidden" name="nh" value="10" />
	        <input type="hidden" name="cs" value="iso-8859-1" />
	        <input type="hidden" name="sc" value="" />  
    	    <input type="hidden" name="sm" value="0" />
	      </td>   
	   
		</tr>
		<input type="hidden" name="ha" value="artscouncil" />

	    <tr>
			<td>
	        <table>
				
			</table>
			</td>
		</tr>
		<tr>
			<td>
			<table>

				<tr>
				<td width="10"><input type="checkbox" name="to" value="1" /></td>
				<td><p>Find in the title only</p></td>
				</tr>
			</table>
			</td>
		</tr>
	</table>

</form>
    </div>
  </div>
</div>     
<div id="greybox">
  <div class="floatleft"><img src="/images/top_left_edging.gif" style="width: 13.1em;" alt="" /></div>
  <div class="floatright"><img src="/images/top_right_edging.gif" style="width: 1.8em;" alt="" border="0" /></div>
  <div class="floatleft" style="padding:2px;"><a href="/index.htm" class="breadcrumb">Home</a></div>  
  <div class="floatright" style="padding:2px;"><a href="../subpages/sitemap.htm" style="font-weight:normal;">Site Map</a></div>

  <div class="floatright" style="padding:2px;"></div>
  <div id="grey_thin_box"><img src="/images/top_grey_edging.gif" style="width: 13.1em;" alt="" border="0" /></div>
</div>
<!-- End TOP BOX -->

<!-- Start Leftside Box -->
<div id="leftside_box">
  <div>
    <div class="menu_link"><a href="/index.htm" class="large bold">Home</a></div>
    <div class="arrow_brown"></div>
  </div>

  <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>
  <div>
    <div class="menu_link"><a href="/artist/index.htm" class="large bold">Featured Artist </a></div>
    <div class="arrow_brown"></div>
  </div>
  <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>
  <div>
    <div class="menu_link"><a href="/subpages/aboutus.htm" class="large bold">About
        Us</a></div>

    <div class="arrow_brown"></div>
  </div>
  <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>
  <div>
    <div class="menu_link"><a href="/subpages/aboutthearts.htm" class="large bold">About the Arts </a></div>
    <div class="arrow_brown"></div>
  </div>
  <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>

  <div>
    <div class="arrow_brown"></div>
  </div>
  <div>
    <div class="menu_link"><a href="/subpages/strategyandpolicies.htm" class="large bold">Funding</a></div>
    <div class="arrow_brown"></div>
  </div>
  
  
  <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>

  <div>
    <div class="menu_link"><a href="../subpages/strategyandpolicies.htm" class="large bold"> Research</a></div>
    <div class="arrow_brown"></div>
  </div>
  
    <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>
  <div>
    <div class="menu_link"><a href="../subpages/compliance.htm" class="large bold">Compliance</a></div>

    <div class="arrow_brown"></div>
  </div>
  
  
  
  <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>
  <div>
    <div class="menu_link"><a href="/foi/index.htm" class="large bold">Freedom of Information </a></div>
    <div class="arrow_brown"></div>
  </div>
  <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>

  <div>
    <div class="menu_link"><a href="/subpages/governance.htm" class="large bold">Governance and Accountability </a></div>
    <div class="arrow_brown"></div>
    <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>
  </div>
  <div>
    <div class="menu_link">
      <p><a href="/subpages/news.htm" class="large bold">News</a></p>

    </div>
    <div class="arrow_brown"></div>
    <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>
  </div>
    <div>
    <div class="menu_link"><a href="/subpages/publications.htm" class="large bold">Publications</a></div>
    <div class="arrow_brown"></div>
    <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>
      </div>
	

  <div>
    <div class="menu_link"><a href="/useful/useful.htm" class="large bold">Useful
        Links</a></div>
    <div class="arrow_brown"></div>
  </div>
  <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>
  <div>
    <div class="menu_link">
      <p><a href="/subpages/newsletter.htm" class="large bold">Mailing List </a></p>

    </div>
    <div class="arrow_brown"></div>
    <div><img src="/images/dotted_line_hori_150.gif" style="width: 13.4em" alt="" border="0" /></div>
  </div>
  <br />
  <br />
  <div class="aligncenter"><a href="http://www.adobe.com/products/acrobat/readstep.html" title="Download the Adobe Acrobat Reader plugin to view PDF documents" target="_blank"><img src="/images/getacro.gif" width="88" height="31" alt="Acrobat Reader icon for viewing PDF Documents" border="0" /></a></div>
  <br />
  <div class="aligncenter"><a href="http://www.w3.org/WAI/WCAG1AA-Conformance" title="Explanation of Level Double-A Conformance" target="_blank"><img height="32" width="88" src="http://www.w3.org/WAI/wcag1AA" alt="Level Double-A conformance icon, W3C-WAI Web Content Accessibility Guidelines 1.0" /></a></div>

</div>
<!-- End Leftside Box -->
<!-- Start CENTER Main Box -->



<div id="center_box">
