<?php
$STRINGS = array
(
	"LANGUAGE"								=> "English",

// Override some of the build in strings
	'NOT_STATED'            						=> '',

// Advanced query Strings
	'FIND_RESULTS'                                                          => 'Find records which include:',
        'SOUNDS_LIKE_THE_WORDS'                                                 => 'words that <b>sounds like</b> the words entered',
        'WITHOUT_THE_WORDS'                                                     => '<b>without</b> the words entered to the right',
        'WITH_ALL_WORDS'                                                        => '<b>all</b> of the words entered to the right',
        'WITH_ANY_WORDS'                                                        => '<b>any</b> of the words entered to the right',
        'WITH_EXACT_PHRASE'                                                     => 'the <b>exact phrase</b> entered to the right',

// Query Form Strings
	"NUMBER_OF_RECORDS"							=> "Records per page",
	"ONLY_WITH_IMAGES"							=> "List items only with images",
	"QUERY_OPTION_ANY"							=> "anywhere",
	"QUERY_OPTION_TAXONOMY"							=> "in taxonomy",
	"QUERY_OPTION_PLACE"							=> "in locations",
	"QUERY_OPTION_PERSON"							=> "in people",

// Display Strings
	"CREATOR"								=> "Creator",

// Catalogue Field Names
        "AdmDateModified"                                                       => "Record Last Modified",
        "AgeGeologicAgeEra_tab"                 				=> "Era",
        "AgeGeologicAgeSeries_tab"      					=> "Series",
        "AgeGeologicAgeSystem_tab"      					=> "System",
        "AgeGeologicAgeSystem:1"	      					=> "System",
        "AgeGeologicAgeStage_tab"                 				=> "Stage",
        "AgeStratigraphyFormation_tab"  					=> "Formation",
        "AgeStratigraphyFormation:1"	  					=> "Formation",
        "AgeStratigraphyGroup_tab"                 				=> "Group",
        "AgeStratigraphyGroup:1"                 				=> "Group",
        "AgeStratigraphyMember_tab"                 				=> "Member",
        "AgeGeologicAgeSystem_tab|AgeGeologicAgeSeries_tab|AgeGeologicAgeStage_tab"	=> "Geologic Time",
        "BioBaySoundLocal"                 					=> "Bay/Sound",
        "BioBiogeographicalRegionLocal"                 			=> "Biogeographical Region",
        "BioChromosomeCount"                            			=> "Chromosome Count",
        "BioCountryLocal"                              				=> "Country",
        "BioCruiseNumberLocal"							=> "Cruise Number",
        "BioDateVisitedFromLocal"                                               => "Date Collected",
        "BioDateVisitedToLocal"                                                 => "Date Visited To",
        "BioDistrictCountyShireLocal"                   			=> "County/District",
        "BioEthnobioUse"                                			=> "Ethnobio Use",
        "BioEthnobioUsedPart"                           			=> "Ethnobio Used Part",
        "BioExpeditionNameLocal"                        			=> "Expedition Name",
        "BioIslandGroupingLocal"                        			=> "Island Grouping",
        "BioIslandNameLocal"                            			=> "Island Name",
        "BioLiveAtCapture"                              			=> "Live At Collection",
        "BioLiveSpecimen"                               			=> "Specimen Description",
        "BioMicrohabitatDescription"                    			=> "Microhabitat Description",
        "BioOceanLocal"                                 			=> "Ocean",
        "BioOceanLocal:1"                               			=> "Ocean",
        "BioParticipantLocal_tab"                       			=> "Collector(s)",
        "BioParticipantRoleLocal_tab"                                           => "Participants Role",
        "BioParticipantStringLocal"                     			=> "Collector(s)",
        "BioPreciseLocationLocal"                       			=> "Precise Locality",
        "BioPreferredCentroidLatitude"                  			=> "Latitude",
        "BioPreferredCentroidLongitude"                 			=> "Longitude",
        "BioPrimaryCollNumber"                                                  => "Primary Coll. Number",
        "BioPrimaryCollNumber"                          			=> "Collection Number",
        "BioPrimaryCollectorLocal"                      			=> "Primary Collector",
        "BioProvinceStateLocal"                         			=> "State/Province",
        "BioProvinceStateLocal:1"                       			=> "Province/State",
        "BioPublishLocalityUser"                                                => "Publish Locality",
        "BioRiverBasinLocal"                            			=> "River Basin",
        "BioSeaGulfLocal"                               			=> "Sea/Gulf",
        "BioSiteNumberLocal"                            			=> "Site/Station Number",
        "BioSubstrate"                                  			=> "Substrate",
        "BioVerbatimLocality"                           			=> "Verbatim Locality",
        "BioVesselNameLocal"                            			=> "Vessel Name",
        "CatBarcode"                                                            => "Barcode",
        "CatCatalog"                                                            => "Catalog",
        "CatCollectionName:1"	                         			=> "Collection Name",
        "CatCollectionName_tab"                         			=> "Collection Name",
        "CatDivision"                                     			=> "Catalog Division",
        "CatNumber"                                     			=> "Catalog Number - USNM",
        "CatOtherNumbersType_tab"                       			=> "Other Numbers Type",
        "CatOtherNumbersValue_tab"                      			=> "Other Numbers",
        "CatPrefix"                                     			=> "Catalog Number Prefix",
        "CatSpecimenCount"                              			=> "Specimen Count",
        "CatSuffix"                                     			=> "Catalog Number Suffix",
        "CitTaxonRefLocal_tab"                          			=> "Type Specimen Name",
        "CitTypeStatus_tab"                             			=> "Primary Type",
        "CitVoucher_tab"                             				=> "Voucher Status",
        "ClaClass_tab"                                  			=> "Class",
        "ClaFamily_tab"                                 			=> "Family",
        "ClaOrder_tab"                                  			=> "Order",
        "ClaPhylum_tab"                                 			=> "Phylum",
        "ColCollectionMethod"                           			=> "Collection Method",
        "ColParticipantRefLocal_tab"                    			=> "Collection Participant",
        "ComName_tab"                                   			=> "Common Name",
        "ExpExpeditionName"                             			=> "Expedition Name",
        "ExpStartDate"                                  			=> "Collection Date",
        "IdeClassLocal_tab"                             			=> "Class",
        "IdeDateIdentified0"                            			=> "Identification Date",
        "IdeFamilyLocal_tab"                            			=> "Family",
        "IdeFiledAsClass"                               			=> "Class",
        "IdeFiledAsDateIdentified"                      			=> "Date Identified",
        "IdeFiledAsFamily"                              			=> "Family",
        "IdeFiledAsGenus"                               			=> "Genus",
        "IdeFiledAsName"                                			=> "Scientific Name",
        "IdeFiledAsOrder"                               			=> "Order",
        "IdeFiledAsPhylum"                              			=> "Phylum",
        "IdeFiledAsQualifiedName"                              			=> "Taxon",
        "IdeFiledAsQualifiedNameWeb"                              		=> "Scientific Name (As Filed)",
        "IdeFiledAsSpecies"                             			=> "Species",
        "IdeFiledAsSubGenus"                            			=> "Sub Genus",
        "IdeFiledAsSubSpecies"                          			=> "Sub Species",
        "IdeFiledAsTypeStatus"                          			=> "Primary Type",
        "IdeFiledAs_tab"                                			=> "Filed As",
        "IdeFiledAsVoucher"                                			=> "Voucher Status",
        "IdeGenusLocal_tab"                             			=> "Genus",
	"IdeCommonNameLocal_tab"						=> "Common Name",
        "IdeIdentifiedByLocal_tab"                      			=> "Identified By",
        "IdeIdentifiedByRefLocal:1"                     			=> "Identified By",
        "IdeIdentifiedByRefLocal_tab"                   			=> "Identified By",
        "IdeKingdomLocal_tab"                   				=> "Kingdom",
        "IdeOrderLocal_tab"                             			=> "Order",
        "IdeOtherQualifiedName_tab"                     			=> "Other Identifications",
        "IdeOtherQualifiedNameWeb_tab"                     			=> "Other Identifications",
        "IdePhylumLocal_tab"                            			=> "Phylum",
        "IdeQualifiedName:1"                            			=> "Qualified Name",
        "IdeQualifiedName_tab"                          			=> "Taxon",
        "IdeScientificNameLocal_tab"                    			=> "Scientific Name",
        "IdeSpeciesLocal_tab"                           			=> "Species",
        "IdeSubGenusLocal_tab"                          			=> "Sub Genus",
        "IdeSubSpeciesLocal_tab"                        			=> "Sub Species",
        "IdeSubfamilyLocal_tab"                         			=> "Subfamily",
        "IdeTypeStatus_tab"                             			=> "Type Status",
        "MeaType_tab"                                   		 	=> "Measurements",
        "MinCountry"                                   			 	=> "Country",
        "MinName"                       					=> "Name",
        "MinState"                                      			=> "Province/State",
        "NotNmnhText0"                                                          => "Notes",
        "PalMorphologyCodes"                                                    => "Skeletal Morphology",
        "SitSiteNumber"                                 			=> "Site/Station Number",
        "SummaryData"                                                           => "Summary Data",
        "VerCollectionMethod"                           			=> "Collection Method",
        "VerStomachContents"                            			=> "Stomach Contents",
        "ZooPreparation"                                			=> "Preparation",
        "ZooPreparation_tab"                            			=> "Preparation",
        "ZooSex_tab"                                    			=> "Sex",
        "ZooStage_tab"                                  			=> "Stage",
        "ZooTemperatureMaxC"                            			=> "Maximum C",
        "ZooTemperatureMinC"                            			=> "Minimum C",
        "ZooTemperatureVerbatim"                        			=> "Verbatim Temp",

// taxonomy fields
	"CitTaxonRef_tab->etaxonomy->ClaScientificName"				=> "Published Name",
	"CitTaxonRef_tab->etaxonomy->PriCitedInRef->ebibliography->SummaryData"	=> "Bibliographic Citations",
	"IdeFiledAsRef->etaxonomy->CitVerificationDegree_tab"                   => "Verification Degree",
        "IdeFiledAsRef->etaxonomy->ClaDivision"                                 => "Division",
        "IdeFiledAsRef->etaxonomy->ClaFamily"                                   => "Family",
        "IdeFiledAsRef->etaxonomy->ClaOrder"                                    => "Order",
        "IdeFiledAsRef->etaxonomy->ClaPhylum"                                   => "Division",
        "IdeFiledAsRef->etaxonomy->ClaSubfamily"                                => "Subfamily",
        "IdeFiledAsRef->etaxonomy->ComName_tab"                                 => "Common Name",
        "IdeFiledAsRef->etaxonomy->GeoAuthorityRef_tab->eparties->SummaryData"  => "Authority",
        "IdeFiledAsRef->etaxonomy->GeoStatus_tab"                               => "Status",
        "IdeFiledAsRef->etaxonomy->WebScientificName"                           => "Scientific Name (As Filed)",
        "IdeTaxonRef_tab->etaxonomy->AutCombAuthorString"                       => "Combined Authors",
        "IdeTaxonRef_tab->etaxonomy->ClaClass"                       		=> "Class",
        "IdeTaxonRef_tab->etaxonomy->ClaOrder"                       		=> "Order",
        "IdeTaxonRef_tab->etaxonomy->ClaFamily"                       		=> "Family",
        "IdeTaxonRef_tab->etaxonomy->ClaKingdom"                       		=> "Kingdom",
        "IdeTaxonRef_tab->etaxonomy->ClaPhylum"                       		=> "Phylum",

// collection events fields
	"BioEventSiteRef->ecollectionevents->ColCollectionMethod"               => "Collection Method",
        "BioEventSiteRef->ecollectionevents->ColDateVisitedConjunction"         => "Date Conjunction",
        "BioEventSiteRef->ecollectionevents->ColDateVisitedFrom"                => "Dates Collected",
        "BioEventSiteRef->ecollectionevents->ColDateVisitedTo"                  => "Date Visited To",
        "BioEventSiteRef->ecollectionevents->ColParticipantLocal_tab"           => "Collector(s)",
        "BioEventSiteRef->ecollectionevents->ColParticipantRole_tab"            => "Participants' Role",
        "BioEventSiteRef->ecollectionevents->ColParticipantString"              => "Collector(s)",
        "BioEventSiteRef->ecollectionevents->ColPrimaryParticipantLocal"        => "Primary Collector",
        "BioEventSiteRef->ecollectionevents->ColVerbatimDate"			=> "Verbatim Date/Time",
        "BioEventSiteRef->ecollectionevents->ExpExpeditionName"		        => "Expedition Name",
	"BioEventSiteRef->ecollectionevents->AquVesselName"			=> "Vessel Name",
	"BioEventSiteRef->ecollectionevents->AquCruiseNumber" 			=> "Cruise Number",
	"BioEventSiteRef->ecollectionevents->LocSiteStationNumber"		=> "Site/Station Number",
        "BioEventSiteRef->ecollectionevents->LatPreferredCentroidLatitude"      => "Centroid Latitude",
        "BioEventSiteRef->ecollectionevents->LatPreferredCentroidLongitude"     => "Centroid Longitude",
        "BioEventSiteRef->ecollectionevents->LocBiogeographicalRegion"          => "Biogeographical Region",
        "BioEventSiteRef->ecollectionevents->LocBaySound"          		=> "Bay/Sound",
        "BioEventSiteRef->ecollectionevents->LocCountry"                        => "Country",
        "BioEventSiteRef->ecollectionevents->LocDistrictCountyShire"            => "County/District",
        "BioEventSiteRef->ecollectionevents->LocGeographicFeatures"             => "Geographic Features",
        "BioEventSiteRef->ecollectionevents->LocIslandName"                     => "Island Name",
        "BioEventSiteRef->ecollectionevents->LocOcean"				=> "Ocean",
        "BioEventSiteRef->ecollectionevents->LocPreciseLocation"                => "Precise Locality",
        "BioEventSiteRef->ecollectionevents->LocProvinceStateTerritory"         => "State/Province",
        "BioEventSiteRef->ecollectionevents->LocSeaGulf"			=> "Sea/Gulf",
        "ColCollectionEventRef->ecollectionevents->ColDateVisitedFrom"          => "Date Collected",
        "ColCollectionEventRef->ecollectionevents->ColDateVisitedTo"            => "Date Visited To",
        "ColCollectionEventRef->ecollectionevents->ColParticipantString"        => "Participants",
        "ColCollectionEventRef->ecollectionevents->ColParticipant_tab"          => "Participants",
        "ColCollectionEventRef->ecollectionevents->ColPrimaryParticipantLocal"  => "Primary Collector",


// parties fields
	"BioCountByRef->eparties->NamBriefName"					=> "Count By",
	"BioParticipantRef_tab->eparties->SummaryData"				=> "Participants",
	"IdeFiledAsIdentifiedByRef->eparties->SummaryData"			=> "Identified By",
	"IdeIdentifiedByRef_tab->eparties->NamBriefName"			=> "Identified By",
	"IdeIdentifiedByRef_tab->eparties->SummaryData"				=> "Identified By",
	"IdeOtherIdentifiedByWebRef_tab->eparties->SummaryData"			=> "Identified By",
        "MinCutByRef->eparties->SummaryData"    				=> "Cut By",
        "MinMakerRef->eparties->SummaryData"    				=> "Made By",

// bibliography fields
	"BibBibliographyRef_tab->ebibliography->SummaryData"			=> "Published",

// predefined table and field array names - across all diciplines
        "Age"                   									=> "Age",
        "AgeStage"              									=> "Age/Stage",
        "AgeGeologicAge"              									=> "Geologic Age",
        "AgeStratigraphy"              									=> "Stratigraphy",
        "ArcClassification1_tab|ArcClassification2_tab|ArcClassification3_tab|ArcClassification4_tab"   => "Site Classification",
        "ArcObjectDateKind_tab|ArcObjectDate_tab|ArcObjectDateModifier_tab|ArcObjectDateVerbatim_tab"   => "Object Date",
        "ArcProvenience1_tab|ArcProvenience2_tab|ArcProvenience3_tab|ArcProvenience4_tab"               => "Site Provenance",
        "AssEvents"             									=> "Associated Events",
        "AssIndividuals"        									=> "Associated Individuals",
        "BirdReprodCondition"   									=> "Reprod. Condition",
        "BotPrepDetails"        									=> "Preparation Details",
        "Bursa"                 									=> "Bursa",
        "CollParticipants"      									=> "Collection Participants",
        "Color"                 									=> "Color",
        "Creators"              									=> "Creators",
        "CulComment_tab"        									=> "Culture Comments",
        "CulCultureLocal:1"             								=> "Culture",
        "CulCultureLocal_tab"   									=> "Culture",
        "CultureList"           									=> "Culture List",
        "DateCollected"         									=> "Date Collected",
        "Depth(m)"              									=> "Depth (m)",
        "DesColor_tab"          									=> "Color",
        "DesManufactTechniques_tab"     								=> "Man. Techniques",
        "DesMaterial_tab|DesPrimaryMat_tab|DesSpecificMaterial_tab"             			=> "Materials",
        "DesObjectDescription:1"        								=> "Object Description",
        "DesObjectDescription_tab"      								=> "Object Description",
        "ErupDetails"           									=> "Eruption Details",
        "FlowTephraDetails"     									=> "Flow/Tephra Details",
        "GeoAgeDetails"         									=> "Geologic Age Details",
        "HerParasites|MamParasite"      								=> "Amphibians & Reptiles - Parasite",
        "IdeClassIndex_tab|IdeIndexTerm_tab|IdeSubType_tab|IdeVariety_tab"      			=> "Identification Details",
        "IdeComments_tab"       									=> "Identification Comments",
        "IdeList"               									=> "Identification List",
        "IdeObjectName"                 								=> "Object Name",
        "IdeObjectName|DesObjectDescription_tab"                                			=> "Object",
        "Materials"             									=> "Materials",
        "Measurements"             									=> "Measurement(s)",
        "MoltDesc"              									=> "Molt Description",
        "ObjectDate"            									=> "Object Date",
        "OtherTerms"            									=> "Other Terms",
        "PhyCauseofDeath_tab|PhyCauseofDeathSource_tab"                         			=> "Cause Of Death",
        "PhyPathCondition_tab|PhyPathConditionSource_tab"                       			=> "Pathalogical Conditions",
        "PhyPathologyKind_tab|PhyPathologyDiagnosis_tab|PhyPathologyComment_tab"			=> "Pathology Details",
        "PhySpecimenClass_tab|PhySpecimenPartName_tab"                          			=> "Specimen Details",
        "PhyStage_tab|PhySource_tab|PhyComments_tab"                            			=> "Age/Stage",
        "ProEvent_tab"          									=> "Associated Events",
        "ProgDetails"           									=> "Progeny Details",
        "ReprodCondition"       									=> "Reprod. Condition",
        "SexAndStage"           									=> "Sex and Stage",
        "SiteClassDetails"      									=> "Site Classification Details",
        "SiteProvDetails"       									=> "Site Provenance Details",
        "Softparts"             									=> "Softparts Details",
        "SpecCount"             									=> "Specimen Count",
        "SpecDates"             									=> "Specimen Dates",
        "SpecDetails"           									=> "Specimen Details",
        "StratDetails"          									=> "StratDetails",
        "SubjectOther"          									=> "Subject Other",
        "SubjectPeople"         									=> "Subject People",
        "TypeCitations"         									=> "Type Citations",
        "ZooPrepDetails"        									=> "Preparation Details",


// Bot fields
        "BotAssociatedFlora"    				=> "Associated Flora",
        "BotCultivated"         				=> "Cultivated",
        "BotHabit"              				=> "Habit",
        "BotPhenology"          				=> "Phenology",
        "BotRecentFossil"       				=> "Recent/Fossil",

// Mammals fields

	"MamInjury"						=> "Injury",
	"MamParasite"						=> "Parasite",
	"MamPhysicalMaturity"					=> "Physical Maturity",
	"MamSexualMaturity"					=> "Sexual Maturity",
	"MamSpecimenCondition"					=> "Specimen Condition",

// Bird fields
        "BirBursaDescription_tab"       			=> "Bursa",
        "BirFat"                        			=> "Fat",
        "BirPlumage"                   			 	=> "Plumage",
        "BirSkull"                      			=> "Skull",
        "BirSoftpartsColor_tab"         			=> "Softparts - Color",
        "BirSoftpartsPart_tab"          			=> "Softparts - Parts",
        "BirTreatment"                  			=> "Treatment",
	
// Herps fields
        "HerBehavioralObservation"      			=> "Amphibians & Reptiles - Behavior",
        "HerColor"                      			=> "Amphibians & Reptiles - Color",
        "HerGrowthData"                 			=> "Amphibians & Reptiles - Growth Data",
        "HerMorphologicalData"          			=> "Amphibians & Reptiles - Morphological Data",
        "HerParasites"                  			=> "Amphibians & Reptiles - Parasites",
        "HerReproductionDescription"    			=> "Amphibians & Reptiles - Reprod. Description",

// Min fields
        "MinAssociatedMinerals_tab"     			=> "Associated Minerals",
        "MinChemicalModifier"           			=> "Chemical Modifier",
        "MinColor"                      			=> "Color",
        "MinCountry"                    			=> "Country",
        "MinCut"                        			=> "Cut",
        "MinDescribedFigured_tab"       			=> "Described",
        "MinJeweleryType"              			 	=> "Jewelery Type",
        "MinMicroprobed"                			=> "Microprobed",
        "MinMineName"                   			=> "Mine Name",
        "MinName"                       			=> "Name",
        "MinState"                      			=> "State",
        "MinSynonyms_tab"               			=> "Synonyms",
        "MinSynthetic"                  			=> "Synthetic",
        "MinWeight"                     			=> "Weight",
        "MinXRayed"                     			=> "X-Rayed",

// Meteorite Fields
        "MetConditionDetermination"             		=> "Condition Determination",
        "MetFindFall"           				=> "Find/Fall",
        "MetMeteoriteName"      				=> "Meteorite Name",
        "MetMeteoriteType"      				=> "Meteorite Type",
        "MetRecordNumber"       				=> "Record Number",
        "MetSynonym"            				=> "Synonym",

// Petrology and Volcanology Fields
        "PetCommodityMetal_tab" 				=> "Commodity Metal",
        "PetEruptionDate"       				=> "Eruption Date",
        "PetFlowTephra"         				=> "Flow/Tephra",
        "PetFlowTephraDate"     				=> "Flow/Tephra Date",
        "PetLavaSource"         				=> "Lava Source",

// Party Field Names
        "BioBirthPlace"         				=> "Birth Place",
        "BioDeathPalce"         				=> "Death Place",
        "BioEthnicity"          				=> "Ethenicity",
        "NamFirst"              				=> "First Name",
        "NamLast"               				=> "Last Name",
        "NamMiddle"             				=> "Middle Name",
        "NamTitle"              				=> "Title",
);
?>
