<?php
$STRINGS = array(
	"LANGUAGE"		=> "English",


// Catalogue Field Names
	"NamObjectTitle"	=> "Title",
	"NamObjectName_tab"		=> "Object Name",
	"NamCommonNames_tab"	=> "Common Names",
	"NamInstrument_tab"		=> "Instrument",
	"NamRecordingFormat_tab"	=> "Recording Format",
	"NamNomenclature_tab"	=> "Nomenclature",
	"SubSubject_tab"	=> "Subject",
	"ClaCategory"		=> "Category",
	"ClaSubCategory"	=> "Sub-Category",
	"ClaType"		=> "Type",
	"ClaSubType"		=> "Sub-Type",
	"ClaClassification"	=> "Classification",
	"ClaCollectionTitle"	=> "Collection Title",
	"CreCreatorRefLocal1:1"	=> "Creator",
	"CreCreatorSummaryData:1"	=> "Creator",
	"CreCreatorSummaryData_tab"	=> "Creator",
	"CreCreatorRef_tab"	=> "Creator",
	"CreCreatorRef->eparties->SummaryData"	=> "Creator",
	"CreCreatorRef_tab->eparties->SummaryData"	=> "Creator",
	"CreCreatorRole_tab"	=> "Creator Role",
	"CrePlaceOfOrigin"	=> "Place of Origin",
	"CreProvenance_tab"	=> "Provenance",
	"CreCulture"		=> "Culture",
	"LocCurrentLocationRef->elocations->SummaryData"	=> "Current Location",
	"AccAccessionLotRef->eaccessionlots->SummaryData"	=> "Accession Information",
	"ObjAccessionNumber"	=> "Accession Number",
	"ObjAccessionDate"	=> "Accession Date",
	"ObjNameOfMuseum"	=> "Name Of Museum",
	"ObjStatus"		=> "Status",
	"ObjPropertyType"	=> "Property Type",
	"ObjCreditLine"		=> "Credit Line",
	"ObjOtherNumberType_tab"	=> "Other Number Type",
	"ObjOtherNumber_tab"	=> "Other Number",
	"NamNomenclature"	=> "Nomenclature",
	"DatDateCreated"	=> "Date Created",
	"DatPeriodOfUse"	=> "Period Of Use",
	"DatDateNotes"		=> "Date Notes",
	"DatUseNotes"		=> "Use Notes",
	"DatCenturyEra"		=> "Century Era",
	"DesInscription_tab"	=> "Inscription",
	"DesInscriptionType_tab"	=> "Inscription Type",
	"DesInscriptionLocation"	=> "Inscription Location",
	"DesObjectDescription"	=> "Object Desciption",
	"DesObjectNotes"	=> "Object Notes",
	"DesMaterials_tab"	=> "Materials",
	"SubSubjectCategory"	=> "Subject Category",
	"SubSubject"		=> "Subject",
	"SubGeographicReference_tab"	=> "Geographic Reference",
	"SubEventReference_tab"	=> "Event Reference",
	"SubPersonReference_tab"	=> "Person Reference",
	"DesMedium_tab"		=> "Medium",
	"DesMaterials"		=> "Materials",
	"DesDescription"	=> "Description",
	"MeaMeasurementNotes"	=> "Measurement Notes",
	"BibBibliographyRef->ebibliography->SummaryData"	=> "Bibliography Notes",
	"MulTitle->emultimedia->SummaryData"	=> "Multimedia Title",
	"MulDescription->emultimedia->MulDescription"	=> "Multimedia Description",
	"NotNotes"		=> "Notes",
	"AdmPublishWebPassword"	=> "Publish on Internet",


// Party Field Names
	"NamTitle"		=> "Title",
	"NamFirst"		=> "First Name",
	"NamLast"		=> "Last Name",
	"NamMiddle"		=> "Middle Name",
	"BioBirthPlace"		=> "Birth Place",
	"BioDeathPalce"		=> "Death Place",
	"BioEthnicity"		=> "Ethenicity",


// Query Form Strings
	"QUERY_OPTION_ANY"	=> "anywhere",
	"QUERY_OPTION_TITLE"	=> "in title",
	"QUERY_OPTION_NOTES"	=> "in notes",
	"QUERY_OPTION_ARTIST"	=> "in artist details",
	"QUERY_OPTION_PLACE"	=> "in creation place",
	"NUMBER_OF_RECORDS"	=> "Records per page",
	"ONLY_WITH_IMAGES"	=> "List works only with images",

// Display Strings
	"CREATOR"		=> "Creator",
	);
?>
