<p class="legal">
	<a title="Accessibility information" href="/accessibility" accesskey="0">Accessibility</a> |
				<a href="/contact" accesskey="c">Contact us</a> | 
				<a href="/complaints" accesskey="7">Complaints</a> | 
				<a href="/copyright">Copyright</a> | 
				<a href="/disclaimer" accesskey="8">Disclaimer / privacy statement</a>
	
	<br />
	<a href="/comments" accesskey="9">Feedback</a> | 
	            <a href="/news" accesskey="2">News</a> |
				<a href="/tis">Translations</a>	|
				<a href="/webstatistics">Website statistics</a>
</p>
<p class="greytext">
	<a href="/redirect/?oid=Category-id-57421">Advice and benefits</a> | 
				<a href="/redirect/?oid=Category-id-57423">Business</a> | 
				<a href="/redirect/?oid=Category-id-57425">Community and living</a> | 
				<a href="/redirect/?oid=Category-id-57427" accesskey="a">Council and democracy</a>  | 
				<a href="/redirect/?oid=Category-id-57429" accesskey="m">Education and learning</a> | 
				<a href="/redirect/?oid=Category-id-57431">Environment and planning</a> | 
				<a href="/redirect/?oid=Category-id-57439">Health and social care</a> | 
				<a href="/redirect/?oid=Category-id-57433">Housing</a> | 
				<a href="/redirect/?oid=Category-id-57435" accesskey="j">Jobs and careers</a> | 
				<a href="/redirect/?oid=Category-id-57437">Leisure and culture</a> | 
				<a href="/redirect/?oid=Category-id-57441">Transport and streets</a>
	
	<a accesskey="l" href="/libraries" class="hide">Libraries</a>
</p>
</div>
</div>
<script type="text/javascript">
			var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
			document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
		</script>
<script type="text/javascript">
			var pageTracker = _gat._getTracker("UA-261764-1");
			pageTracker._initData();
			pageTracker._trackPageview();
		</script>
<script type="text/javascript" src="/includes/socitmSurvey.js">
                 
                </script>
<noscript>
<a href="http://socitm.govmetric.com/survey.aspx?code=78">Tell us what you think about our site...</a>
<img alt="" src="http://socitm.govmetric.com/imagecounter.aspx?code=78" />
</noscript>
</body>
</html>
<!-- end footer.inc -->
