<?php

// ATTENTION: This file is automatically generated.
// DO NOT MODIFY.

global $LUTS_CACHE;
global $REGISTRY_CACHE;

$LUTS_CACHE["system approved"] = "Approved";
$LUTS_CACHE["system book"] = "Book";
$LUTS_CACHE["system closed"] = "Closed";
$LUTS_CACHE["system disapproved"] = "Disapproved";
$LUTS_CACHE["system external"] = "External";
$LUTS_CACHE["system female"] = "Female";
$LUTS_CACHE["system finish"] = "Finish";
$LUTS_CACHE["system holder"] = "Holder";
$LUTS_CACHE["system incoming"] = "Incoming";
$LUTS_CACHE["system internal"] = "Internal";
$LUTS_CACHE["system journal"] = "Journal";
$LUTS_CACHE["system location"] = "Location";
$LUTS_CACHE["system male"] = "Male";
$LUTS_CACHE["system months"] = "Months";
$LUTS_CACHE["system no"] = "No";
$LUTS_CACHE["system not applicable"] = "Not Applicable";
$LUTS_CACHE["system open"] = "Open";
$LUTS_CACHE["system other"] = "Other";
$LUTS_CACHE["system outgoing"] = "Outgoing";
$LUTS_CACHE["system pending"] = "Pending";
$LUTS_CACHE["system start"] = "Start";
$LUTS_CACHE["system thesis"] = "Thesis";
$LUTS_CACHE["system unknown"] = "Unknown";
$LUTS_CACHE["system years"] = "Years";
$LUTS_CACHE["system yes"] = "Yes";

$REGISTRY_CACHE["system-setting-language-show empty delimiters"] = "false";
$REGISTRY_CACHE["system-setting-language-show first filled"] = "false";
$REGISTRY_CACHE["system-setting-language-show trailing delimiters"] = "false";
$REGISTRY_CACHE["system-setting-language-supported"] = "0";

?>
