<?php
$STRINGS = array(
	"LANGUAGE"		=> "English",
	"IMAGE"			=> "IMAGE",
	'NEW SEARCH'            => 'New search',
	'PREVIOUS'		=> 'Previous page',
	'NEXT'			=> 'Next page',

// Catalogue Field Names
	"TitMainTitle"		=> "Title",
	"TitSeriesTitle"	=> "Series Title",
	"TitCollectionTitle"	=> "Collection Title",
	"CreCreatorLocal:1"	=> "Creator",
	"CreCreatorLocal_tab"	=> "Creator",
	"CreCreatorRef_tab"	=> "Creator",
	"LocCurrentLocationRef->elocations->SummaryData"	=> "Current Location",
	"AccAccessionLotRef->eaccessionlots->SummaryData"	=> "Accession Information",
	"TitTitleNotes"		=> "Title Notes",
	"TitAccessionNo"	=> "Registration Number",
	"TitAccessionDate"	=> "Accession Date",
	"CreDateCreated"	=> "Date Created",
	"CrePrimaryInscriptions"=> "Inscription",
	"CreTertiaryInscriptions"=> "Tertiary Inscription",
	"CreSubjectClassification"=> "Subject Classification",
	"PhyMedium"		=> "Medium",
	"PhySupport"		=> "Support",
	"PhyTechnique"		=> "Technique",
	"PhyMediaCategory"	=> "Media Category",
	"NotNotes"		=> "General Notes",
	"CreCountry_tab"	=> "Created In",
	"AdmPublishWebPassword"	=> "Publish on Internet",
	"SumTitle"		=> "Title",
	"SumAccessionNumber"	=> "Accession no.",
	"SumDate"		=> "Date",
	"SumDateEarliestLower"	=> "Date range:&nbsp;&nbsp;&nbsp;&nbsp;Earliest",
	"SumDateLatestUpper"		=> "Date range:&nbsp;&nbsp;&nbsp;&nbsp;Latest",
	"SummaryData"		=> "Summary Data",
	"ArtSurnameLocal"	=> "Creator/Culture:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Surname",
	"ArtCulturalIdentityLocal"	=> "Cultural identity",
	"ArtArtistLocal"	=> "Creator/Culture",
	"ArtDimensionsA"	=> "Dimensions a",
	"ArtDimensionsB"	=> "Dimensions b",
	"ArtCreditLine"		=> "Credit line",
	"SumDepartment"		=> "Department",
	"SumSearchCat"		=> "Search category",
	"ArtMediaCategory"	=> "Media category",
	"SumMedium"		=> "Medium",
	"SumSupport"		=> "Support",
	"ArtGivenNameLocal"	=> "Given name/s",
	"ArtArtistRef_tab->eparties->BioNationality"	=> "Principal country",
	"ArtPrincipalCountryLocal"	=> "Principal country",
	"ArtArtistRef_tab->eparties->BioState"		=> "State",
	"ArtStateLocal"		=> "State (eg. QLD, NSW, VIC, SA, TAS, NT, WA, ACT)",
	"ArtArtistRef_tab->eparties->NamSex"		=> "M/F",
	"ArtGenderLocal"	=> "M/F",
	"ArtArtistRef_tab->eparties->BioBirthDate"	=> "Born",
	"ArtBirthDateLocal"	=> "Born",
	"ArtArtistRef_tab->eparties->BioDeathDate"	=> "Died",
	"ArtDeathDateLocal"	=> "Died",
	"ArtArtistRole_tab"	=> "Role",
	"ArtEdition"	=> "Edition",
	"RefExhibitionHistory"		=> "Exhibition history",
	"RefReferences"		=> "References",
	"RefReproductions"	=> "Reproductions",
	"RefReproductions|RefReferences"	=> "References/Reproductions",
	"RefAdditionalInformation" 	=> "Additional information",
	"FIND"			=> "Keyword/s",
	"Creator/CultureORTitle" => "Creator/Culture OR Title",
	"FIND_RESULTS"		=> "Find results:",

// Party Field Names
	"NamTitle"		=> "Title",
	"NamFirst"		=> "Given Name",
	"NamLast"		=> "Last Name",
	"NamMiddle"		=> "Middle Name",
	"BioBirthPlace"		=> "Birth Place",
	"BioDeathPalce"		=> "Death Place",
	"BioEthnicity"		=> "Ethenicity",
	"BioBirthDate"		=> "Born",
	"BioDeathDate"		=> "Died",


// Query Form Strings
	"QUERY_OPTION_ANY"	=> "Anywhere",
	"QUERY_OPTION_TITLE"	=> "Title",
	"QUERY_OPTION_NOTES"	=> "in notes",
	"QUERY_OPTION_ARTIST"	=> "in artist details",
	"QUERY_OPTION_PLACE"	=> "in creation place",
	"NUMBER_OF_RECORDS"	=> "Records per page",
	"ONLY_WITH_IMAGES"	=> "List works only with images",

// Display Strings
	"CREATOR"		=> "Creator",
	"NEXTRECORD"		=> "Next record",
	"PREVRECORD"		=> "Previous record",
	"BACKTORESULTS"		=> "Back to list",
	);
?>
