<!DOCTYPE html 
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <link rel="stylesheet" type="text/css" href="css/style.css"></link>
    <title>Royal Academy of Music museum collections</title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
  </head>
  <body>
    <div id="outerContainer" class="alignCenter">
    <table width="786px" border="0" cellspacing="2" cellpadding="0">
      <tr> 
        
       <td colspan="1" class="pageHeaderYG">
       <a href="http://www.ram.ac.uk"><img src="images/RAM.jpg" alt="RAM Home Page"  border="0"/></a><a href="http://www.yorkgate.ram.ac.uk/emuweb/pages/ram/Query.php"><img src="images/limehead.jpg" alt="Apollo Home Page"  border="0"/></a><img src="images/limebanner4.jpg"   border="0"/></td>


	</tr>
      <tr> 
       <td></td> 
      </tr>
      <tr> 
        <td colspan="2" class="backgroundDocument">
          <!-- Body Section Start -->
