<?php
$STRINGS = array(
        "LANGUAGE"              => "English",
	"QUERY_OPTION_INSUBJECT"	=> "in Subject",
	"NEW SEARCH"	=>	"New Search and Help",
	'TitBriefDescription'	=> "Title",
	'RigRightsRef_tab->erights->SummaryData' => "Copyright",
	'TitObjectType' => "Object Type",
	'TitCollection' => "Collection",
	'CreCreatorRef_tab->eparties->SummaryData' => "Artist/Maker",
	'CreRole_tab' => "Creator role",
	'CreDateCreated' => "Date made",
	'CreCountry_tab|CreState_tab|CreDistrict_tab|CreCity_tab' => "Place of creation",
	'TitFullDescription' => "Description",
	'CrePrimaryInscriptions' => "Primary inscription",
	'NotNotes' => "Notes",
	'AssRelatedPartiesRef_tab->eparties->SummaryData' => "People",
	'AssRelationship_tab' => "Roles",
	'PhyTechnique_tab' => "Technique",
	'PhyClassification' => "Classification",
	'PhyMaterials_tab' => "Materials",
	'TitAccessionNo' => "Accession No.",
	'CreCreatorRef_tab->eparties->BioBirthDate' => "Creators date of birth",
	'CreCreatorRef_tab->eparties->BioBirthPlace' => "Creators place of birth",
	'CreCreatorRef_tab->eparties->BioDeathDate' => "Creators date of death",
	'CreCreatorRef_tab->eparties->BioDeathPlace' => "Creators place of death",
	'CreCreatorRef_tab->eparties->BioNationality' => "Creators nationality",
	'CreCreatorRef_tab->eparties->NotNotes' => "Creators biographical notes",
	'NamFirst' => 'First name',
	'NamLast' => 'Last name',
	'NamMiddle' => 'Middle name',
	'BioBirthPlace' => 'Place of Birth',
	'BioBirthDate' => 'Date of Birth',
	'BioDeathPlace' => 'Place of Death',
	'BioDeathDate' => 'Place of Death',
	);
?>
