<?php
$STRINGS = array(
	"LANGUAGE"		=> "English",


// Catalogue Field Names
	"CatType"		=> "Record Type",
	"TitCollectionTitle"    => "Collection Title",
	"TitAccessionNo"        => "Accession Number",
	"CatDepartment"		=> "Department",
	"PhyMediumCategory"	=> "Classification",
	"CreCreatorLocal_tab"	=> "Creator Details",
	"CreCreatorLocal:1"	=> "Creator Details",
	"TitMainTitle"          => "Title",
	"AcqCreditLine" 	=> "Credit Line",
	"CreDateCreated"        => "Date Created",
	"CreEarliestDate"	=> "Earliest Date",
	"CreLatestDate"		=> "Latest Date",
	"CreCentury"		=> "Century",
	"LocCurrentLocationLocal"	=> "Current Location",
	"PhyMedium_tab"         => "Media and Materials",
	"PhyTechnique"		=> "Processes and Tools",
	"CatSubject"            => "Subjects",
	"CatStyle"		=> "Styles/Period",
	"AdmPublishWebPassword"	=> "Publish on Internet",
	"AccAccessionLotRef->eaccessionlots->SummaryData"       => "Accession Information",
	"TitTitleNotes"         => "Title Notes",
	"PhyInscriptions"	=> "Inscriptions",
	"CrePrimaryInscriptions"=> "Inscription",
	"CreTertiaryInscriptions"=> "Tertiary Inscription",
	"CreSubjectClassification"=> "Subject Classification",
	"NotNotes"              => "General Notes",
	"CreCountry_tab"        => "Created In",
	"CreRole_tab"		=> "Role",
	"EdiEdition"		=> "Edition",
	"PhyMediumComments"	=> "Medium Description",
	"MesMeasurementType_tab"	=> "Measurement Type",
	"MesTotalInchFrac_tab"	=> "Height",
	"MesTotWidthInchFrac_tab"	=> "Width",
	"MesTotDepthInchFrac_tab"	=> "Depth",
	"MesTotDiamInchFrac_tab"	=> "Diameter",
	"AssChildObjRef_tab"	=> "Child Objects",
	"AssParentObjectRef->ecatalogue->SummaryData"	=> "Parent Objects",
	"AssRelatedObjectsRef_tab->ecatalogue->SummaryData"	=> "Related Objects",
	"AssRelationship_tab"	=> "Relationship",
	"EveEvents_tab"	=> "Events Description",

// Party Field Names
	"NamTitle"		=> "Title",
	"NamFirst"		=> "First Name",
	"NamLast"		=> "Last Name",
	"NamMiddle"		=> "Middle Name",
	"BioBirthDate"		=> "Birth Date",
	"BioDeathDate"		=> "Death Date",
	"BioNationality"	=> "Nationality",
	"BioBirthPlace"		=> "Birth Place",
	"BioDeathPlace"		=> "Death Place",
	"BioCommencementDate"	=> "Commencement Date",
	"BioCompletionDate"	=> "Completion Date",
	"BioCommencementNotes"	=> "Commencement Notes",


// Query Form Strings
	"QUERY_OPTION_ANY"	=> "anywhere",
	"QUERY_OPTION_TITLE"	=> "in title",
	"QUERY_OPTION_CREATOR"	=> "in creator details",
	"NUMBER_OF_RECORDS"	=> "Records per page",
	"ONLY_WITH_IMAGES"	=> "List only works with images",
	"QUERY_OPTION_ACCESSION" => "in accession no",
	"QUERY_OPTION_DEPT"	=> "in department",
	"QUERY_OPTION_CLASS"	=> "in classification",
	"QUERY_OPTION_CREDIT" 	=> "in credit line",
	"QUERY_OPTION_TYPE"	=> "in record type",
	"QUERY_OPTION_PLACE"    => "in creation place",
	"QUERY_OPTION_COLL"     => "in collection title",
	"QUERY_OPTION_DATE"     => "in date",
	"QUERY_OPTION_EARLY"    => "in earliest date",
	"QUERY_OPTION_LATE"     => "in latest date",
	"QUERY_OPTION_CENTURY"  => "in century",
	"QUERY_OPTION_LOC"      => "in current location",
	"QUERY_OPTION_MEDIA"    => "in media & materials",
	"QUERY_OPTION_PROCESS"  => "in processes & tools",
	"QUERY_OPTION_SUBJECTS"  => "in subjects",
	"QUERY_OPTION_STYLE"    => "in styles & period",


// Display Strings
	"CREATOR"		=> "Creator",
	"MEASUREMENTS"		=> "Measurements",
	"CHILD"			=> "Child Objects",
	"RELATION"		=> "Related Objects",
	);
?>
