<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
	<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
  		<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
  		<link type="text/css" rel="stylesheet" href="css/style.css" />
  		<script type="text/javascript" src="javascript/jquery/jquery-1.3.1.min.js"></script>
  		<title>Bristol City Council: Museum collections BMGA Intranet </title>
		<!--
						EDIT: /redirect/?oid=Article-id-28284024&context=draft
					-->
		<meta content="Article-id-28284024" name="BCC.oid" />
		<meta content="7CY1+H0x3As2Ohax2fB3byXcju/EVHIP7vTGEsAhDjU=" name="verify-v1" />
		<meta name="DC.title" content="Bristol City Council: Museum collections" />
		<meta content="An intruduction to our collections- index page " name="description" />
		<meta content="Double-A" scheme="WCAG" name="eGMS.accessibility" />
		<meta scheme="LGAL" content="" name="DCTERMS.audience" />
		<meta content="Bristol, South West, UK" name="DC.Coverage" lang="en" />
		<meta scheme="URI" name="DC.identifier" content="http://www.bristol.gov.uk/ccm/navigation/leisure-and-culture/museums-and-galleries/museum-collections/" />
		<meta content="24-Oct-2008" name="DC.date" />
		<meta content="text/html" name="DC.format" />
		<meta content="" scheme="ONS SNAC" name="DC.coverage.spatial" />
		<meta content="Bristol City Council" name="DC.creator" />
		<meta content="Bristol City Council" name="DC.publisher" />
		<meta scheme="ISO 639-2" content="en" name="DC.language" />
		<meta content="http://www.bristol.gov.uk/copyright" name="DC.rights" />
		<meta content="/ccm/portal?output=xml" name="DC.relation.isFormatOf" />
		<meta content="Bristol City Council service information" name="DC.subject" />
		<meta scheme="IPSV" content="Internet" name="eGMS.subject.category" />
		<meta scheme="LGNL" content="1018" name="eGMS.subject.service" />
		<meta scheme="IPSV" content="Museums and galleries" name="eGMS.subject.category" />
		<link charset="iso-8859-1" type="text/css" href="/css/bccGlobal.css" rel="stylesheet" />
		<link charset="iso-8859-1" type="text/css" href="/css/bccLeisure.css" rel="stylesheet" />
		<link charset="iso-8859-1" type="text/css" media="print" href="/css/print.css" rel="stylesheet" />
		<link charset="iso-8859-1" type="text/css" href="/css/bcc-siteproxy.css" rel="stylesheet" />
		<script type="text/javascript" src="javascript/main.js"></script>
	</head>
	<body>
		<div class="gainlayout" id="accessLinks">
			<ul>
			<li class="hide">
			<a accesskey="s" href="#content" title="skip to content">Skip to main content</a>
			</li>
			<li class="hide">
			<a accesskey="5" href="#navigation" title="skip to main navigation">Skip to main Navigation</a>
			</li>
			</ul>
		</div>
		<div id="logo">
			<a href="http://www.bristol.gov.uk/ccm">
			<img style="display: block;" title="Bristol City Council logo and link to homepage" alt="Bristol City Council" src="/images/logo.gif" />
			</a>
		</div>
		<div id="masthead1">
			<img style="display: block;" alt="" src="/images/masthead1.gif" width="100%" height="81" />
		</div>
		<div id="masthead2">
			<img style="display: block;" alt="" src="/images/masthead2.gif" width="100%" height="81" />
		</div>
		<div id="sectiontext">
			<img title="museum collections" alt=" museum collections" src="/images/sectiontext.gif" />
		</div>
		<div id="navimage">
			<a href="http://www.bristol.gov.uk/ccm" accesskey="1">
				<img class="navimagelink" alt="" title="Bristol City Council" src="/images/trans.gif" width="1" height="1" />
			</a>
		</div>
			<div id="navbar">
				<span id="navlinks">
					<a href="http://www.bristol.gov.uk/ccm/atoz/" accesskey="3">a-z index</a> | 
													<a href="http://www.bristol.gov.uk/ccm/navigation/sitemap.jsp">site map</a> | 
													<a href="http://www.bristol.gov.uk/services">online services</a> | 
													<a href="http://www.bristol.gov.uk/contact" accesskey="c">contact</a> | 
													<a href="http://www.bristol.gov.uk/help" accesskey="6">help</a>
				</span>
				<span style="visibility: visible;" id="search">
					<input id="searchbox" size="20" value="" name="query" type="text" />
					<input id="searchgobutton" value="Search" name="submit" accesskey="4" type="submit" />
					<label style="visibility: hidden;" for="searchbox">Search Text</label>
				</span>
			</div>

		<div class="catPath">You are here &gt; <a href="http://www.bristol.gov.uk/ccm/portal/">Home</a>&nbsp;&gt; <a class="down" href="http://www.bristol.gov.uk/redirect/?oid=Category-id-57437">Leisure&nbsp;and&nbsp;culture</a>&nbsp;&gt; <a class="down" href="http://www.bristol.gov.uk/redirect/?oid=Category-id-57579">Museums&nbsp;and&nbsp;galleries</a>&nbsp;&gt; Museum&nbsp;collections</div>
		<div class="holder">
			<div class="gainlayout" id="navigation">
				<ul class="nav">
					<li class="up">
						<a title="Go to homepage" class="up" href="http://www.bristol.gov.uk/ccm/portal/">
							Home
						</a>
					</li>
					<li class="up">
						<a class="up" href="http://www.bristol.gov.uk/redirect/?oid=Category-id-57437" title="Go up to Leisure and culture">Leisure and culture</a>
					</li>
					<li class="up">
						<a class="up" href="http://www.bristol.gov.uk/redirect/?oid=Category-id-57579" title="Go up to Museums and galleries">Museums and galleries</a>
					</li>
					<li class="this">Museum collections</li>
				</ul>
				<img alt=" " src="/images/trans.gif" />
			</div>
		<div class="gainlayout" id="content">
<!-- end header.inc -->

