<?php
$STRINGS = array(
	"LANGUAGE"		=> "English",

	'SummaryData'	=>	"Specimen Summary",
	'MinGroup'	=>	"Collection Category",
	'MinBmNumber'	=>	"Registration No.",
	// Type Status? 'TypTypeStatus_tab',
	'MinIdentificationAsRegistered'	=>	"Name as Registered",
	'MinIdentificationRef->etaxonomy->SummaryData'	=>	"Current Name",
	'MinIdentificationText'	=>	"Current Name",
	'MinPetIdentificationCommercial'	=>	"Commercial Name",
	'MinMetChondriteAchondrite'	=>	"(A)chondrite",
	'MinMetType'	=>	"Type",
	'MinMetClass'	=>	"Class",
	'MinMetGroup'	=>	"Group",
	'MinIdentificationRef->etaxonomy->ClaSoiUSDAOrder'	=>	"USDA Order",
	'MinIdentificationRef->etaxonomy->ClaSoiFAOOrder'	=>	"FAO-UNESCO Order",
	'MinOreDepositType'	=>	"Deposit Type",
	'MinColour'	=>	"Colour",
	'MinSoiTexture'	=>	"Texture",
	'MinOreCommodity'	=>	"Commodity",
	'MinOBDCollectionEventRef->ecollectionevents->SummaryData'	=>	"Collection Event",
	'MinLocalityRef->esites->SummaryData'	=>	"Locality",
	'MinAccessionLotRef->eaccessionlots->SummaryData'	=>	"Accession Summary",
	'MinLocalityRef->esites->LocOcean_tab'	=>	"Ocean",
	'MinLocalityRef->esites->LocIslandName'	=>	"Island",
	'MinLocalityRef->esites->LocCountry_tab'	=>	"Country",
	'MinLocalityRef->esites->LocProvinceStateTerritory_tab'	=>	"State",
	'MinLocalityRef->esites->LocDistrictCountyShire_tab'	=>	"County",
	'MinNhmVerbatimLocalityLocal'	=>	"Verbatim Locality",
	'MinLocalityRef->esites->LatLatitude_nesttab|MinLocalityRef->esites->LatLatitudeDecimal_nesttab|MinLocalityRef->esites->LatLatitudeDM_nesttab|MinLocalityRef->esites->LatLatitudeDM_nesttab'	=>	"Latitude",
	'MinLocalityRef->esites->LatLongitude_nesttab|MinLocalityRef->esites->LatLongitudeDecimal_nesttab|MinLocalityRef->esites->LatLongitudeDM_nesttab|MinLocalityRef->esites->LatLongitudeDM_nesttab'	=>	"Longitude",
	'MinLocalityRef->esites->GeoNhmComplex'	=>	"Geological Complex",
	'MinLocalityRef->esites->GeoNhmStandardMine'	=>	"Quarry / Mine",
	'MinLocalityRef->esites->GeoNhmLithostrat'	=>	"Lithostratigraphy",
	'MinMetRecoveryFindFall'	=>	"Fall or Find",
	'MinMetRecoveryDate'	=>	"Date of Fall / Find",
	'MinIdentificationRef->etaxonomy->SummaryData|MinIdentificationText'	=>	"Current Name",
	'MinOBDCollectionEventRef->ecollectionevents->SummaryData|MinLocalityRef->esites->SummaryData'	=>	"Collection Event / Locality",	
	"MinLocalityRef->esites->LatCentroidLongitude0"	=>	"Longitude",
	"MinLocalityRef->esites->LatCentroidLatitude0"	=>	"Latitude",
	);
?>
